import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import NavbarComponent from "@/component/navbar/NavbarComponent";
import FooterComponent from "@/component/footer/FooterComponent";
import { roboto, suwannaphum } from "./fonts";
import StoreProvider from "../StoreProvider";
import { Providers } from "../providers";
import SessionWrapper from "../SessionWrapper";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={`${suwannaphum.variable} ${roboto.variable}`}>
          <StoreProvider>
            <Providers>
              <NavbarComponent />
              {children}
              <FooterComponent />
            </Providers>
          </StoreProvider>
        </body>

      </SessionWrapper>
    </html>
  );
}
